development:
 secret_key_base: somerandomkey
test:
 secret_key_base: somerandomkey
staging:
 secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
production:
 secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

# development:

  # secret_token: "my_secret_token"
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>


  # secret_key_base: "abcdef0123456789"


# secrets.secret_key_base

# development:
#   secret_key_base: a75d...

# test:
#   secret_key_base: 492f...

# production:
#   secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>